### POST request to create patients
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Arzav Jain",
  "email": "arzav.j@gmail.com",
  "address": "New Delhi, India",
  "dateOfBirth": "2000-09-14",
  "registeredDate": "2026-03-31"
}
###