spring.application.name=patient-service
server.port=4000
logging.level.root=info
# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://patient-service-db:5432/db
spring.datasource.username=admin_viewer
spring.datasource.password=password
# JPA CONFIG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
billing.service.address=billing-service
billing.service.grpc.port=9001
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer